config/routes.rb
Rails.application.routes.draw do
  resources :exams
  resources :questions
  get 'welcome/index'
  get 'questions_exams/regeneratetests'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'welcome#index'
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :questions_exams
    has_many :exams, through: :questions_exams
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        regeneratetests()        
        format.html { redirect_to @question, notice: 'Question was successfully created. And Exams have been generated' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.exams.destroy_all
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :obs, :question_type)
    end

    def regeneratetests
      QuestionsExamsController.regeneratetests()
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, :class => 'form-control', :required => true %>
  </div>

  <div class="field">
    <%= form.label :question_type %>
    <%= form.select :question_type,  options_for_select([['Practice', 0], ['Exam', 1]], @question.question_type),
          {:include_blank => true, :selected_value => nil }, :class=>'form-control', :required => true %>
  </div>


  <div class="field" id="group-obs">
    <%= form.label :obs %>
    <%= form.text_field :obs, :class => 'form-control', :required => true %>
  </div>

  
  <div class="actions">
    <%= form.submit :class=>"btn btn-primary" %>
  </div>
<% end %>

<script>
$(document).ready(function(){
  $("#group-obs").hide();
  $("#question_question_type").change(function(e){
    if ($(this).val() === "0"){
      $("#group-obs").show('slow').children('label').html("Explanation");
      $("input[name='commit']").attr("disabled",false);
    }else if ($(this).val() === "1"){
      $("#group-obs").show('slow').children('label').html("Hint");
      $("input[name='commit']").attr("disabled",false);
    }else{
      $("#group-obs").hide('slow');
      $("input[name='commit']").attr("disabled",true);
    }
  });

});
</script>

app/views/questions/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1>Editing Question</h1>
            <%= render 'form', question: @question %>
            <%= link_to 'Show', @question %> |
            <%= link_to 'Back', questions_path %>
        </div>
    </div>
</div>

app/views/questions/index.html.erb
<main role="main" class="container">

  <div class="starter-template">
    <h1>Questions</h1>
    
    <p class="lead">List of questions for practice and for exam.</p>
    <br>
    <p id="notice"><%= notice %></p>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>[Hint | Explanation]]</th>
          <th>Question type</th>
          <th style="width:220px;">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% contador = 0 %>
        <% @questions.each do |question| %>
        <% contador += 1 %>
          <tr>
            <td class="text-left"><%= contador %>.<%= question.title %></td>
            <td><%= question.obs %></td>
            <td><% if question.question_type === 0 %>
                    <span class="badge badge-primary"><%= 'Practice Question' %></span>
                  <% else %>
                    <span class="badge badge-dark"><%= "Exam Question" %></span>
                  <% end %> 
            </td>      
            <td><%= link_to 'Show', question , :class => 'btn btn-sm btn-info', :style => 'color:white;' %>
                            <%= link_to 'Edit', edit_question_path(question), :class => 'btn btn-sm btn-primary', :style => 'color:white;' %>
              <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger', :style => 'color:white;' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>
  <br>
  <%= link_to 'New Question', new_question_path, :class => 'btn btn-primary', :style => 'color:white;' %>

</main><!-- /.container -->

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1>Editing Question</h1>
            <br>
            <label for="exampleInputEmail1">Title</label>
            <input class="form-control" value="<%= @question.title %>" disabled>
            <br>
            <label for="exampleInputEmail1"><%= @question.question_type == 0 ? "Hint" : "Explanation" %></label>
            <input class="form-control" value="<%= @question.obs %>" disabled>
            <br>
            <label for="exampleInputEmail1">Question type</label>
            <input class="form-control" value="<%= @question.question_type == 0 ? "Practice" : "Exam" %>" disabled>
            <br>

            <%= link_to 'Edit', edit_question_path(@question) %> |
            <%= link_to 'Back', questions_path %>

        </div>
    </div>
</div>