config/routes.rb
Rails.application.routes.draw do
  resources :exams
  resources :questions
  get 'welcome/index'
  get 'questions_exams/regeneratetests'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'welcome#index'
end

app/models/exam.rb
class Exam < ApplicationRecord
    has_many :questions_exams
    has_many :questions, through: :questions_exams
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  layout "application"
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    
    @exams = Exam.all
    
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
    @questions = @exam.questions.all
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save

        regeneratetests

        format.html { redirect_to @exam, notice: 'Exam was successfully created. And Exams have been generated' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.questions.destroy_all
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:name, :exam_type)
    end

    def regeneratetests
      QuestionsExamsController.regeneratetests()
    end


end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :class => 'form-control', :required => true %>
  </div>

  <div class="field">
    <%= form.label :exam_type %>
    <%= form.select :exam_type,  options_for_select([['Practice', 0], ['Exam', 1]], @exam.exam_type),
          {:include_blank => true, :selected_value => nil }, :class=>'form-control', :required => true %>
  </div>

  <div class="actions">
    <%= form.submit :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1>Editing Exam</h1>
            <%= render 'form', exam: @exam %>
            <%= link_to 'Show', @exam %> |
            <%= link_to 'Back', exams_path %>
        </div>
    </div>
</div>

app/views/exams/index.html.erb
<main role="main" class="container">

  <div class="starter-template">
    <h1>Tests</h1>
    
    <p class="lead">List of test for practice and for exam.</p>
    <br>
    <p id="notice"><%= notice %></p>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Exam type</th>
          <th style="width:220px;">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% contador = 0 %>
        <% @exams.each do |exam| %>
        <% contador += 1 %>
          <tr>
            <td class="text-left"><%= contador %>.<%= exam.name %></td>
            <td><% if exam.exam_type === 0 %>
                    <span class="badge badge-primary"><%= 'Practice Test' %></span>
                  <% else %>
                    <span class="badge badge-dark"><%= "Exam Test" %></span>
                  <% end %> 
            </td>
            <td><%= link_to 'Show', exam , :class => 'btn btn-sm btn-info', :style => 'color:white;' %>
            <%= link_to 'Edit', edit_exam_path(exam), :class => 'btn btn-sm btn-primary', :style => 'color:white;' %>
            <%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger', :style => 'color:white;' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
  </div>

  <%= link_to 'New Exam', new_exam_path, :class => 'btn btn-primary', :style => 'color:white;' %>

</main><!-- /.container -->

app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1>Editing Exam</h1>
            <br>
            <label for="exampleInputEmail1">Name</label>
            <input class="form-control" value="<%= @exam.name %>" disabled>
            <br>
            <label for="exampleInputEmail1">Exam Type</label>
            <input class="form-control" value="<%= @exam.exam_type == 0 ? "Practice" : "Exam" %>" disabled>
            <br>

            <%= link_to 'Edit', edit_exam_path(@exam) %> |
            <%= link_to 'Back', exams_path %>
        </div>

        <div class="col-md-8 offset-md-2">
            
            <br>
            <table class="table table-striped">
      <thead>
        <tr>
          <th style="width:220px;">Questions in the Test</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% contador = 0 %>
        <% @questions.each do |question| %>
        <% contador += 1 %>
          <tr>
          <td colspan="2">
            <h6 class="text-left"><%= contador %>.<%= question.title %></h6>
            <%= @exam.exam_type == 0 ? "Hint" : "Explanation" %>: <span style="font-style:oblique;"><%= question.obs %><span></td>
          </tr>
        <% end %>
      </tbody>
    </table>
            <%= link_to 'Back', exams_path %>
        </div>
    </div>
</div>